
project:
  type: website
  output-dir: docs

website:
  title: "CHange"
  navbar:
    left:
      - href: HomeAbout.qmd
        text: About Me
      - href: ContactInfo.qmd
        text: Contact
      - text: Portfolio
        menu:
          - href: certifications.qmd
            text: Certifications
          - href: Projects.qmd
            text: Projects
output-dir: docsaving

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

